### ISSUE TITLE
DevOps: Cleanup Docker image and entrypoint

### ISSUE THREAD

**Issue by andypotanin** [boxmls/service-poller#4]
General cleanup and maintenance.

* [x] Remove mention of `ssh-keyscan`, `~/.ssh`, etc. and other stuff related to us doing `git pull` from inside the container.
* [x] Remove directories like `etc/git-hooks` and other `/etc/*` and any other directories/files for services we no longer use or install - like `monit`, and others.
* [x] Remove the `git pull` method from entrypoint files - everything needed should be packaged into the image to run without needing to communicate with github again.
* [x] Make sure that pm2 is used for all inner-services and they are all defined in an `ecosystem.config.js` in root of each repository.
* [x] Replace private NPM module dependencies (such as `@mypropertyoffice/docker-healthcheck`) in package.json with `boxmls/node-docker-healthcheck` - this will make npm load the public modules directly from GitHub.
* [x] Make sure that the Dockerfile `CMD` runs `pm2 logs --json` so that all pm2 logs are streamed to docker. 
* [x] Update readme.md to include the build command (don't use `bin/build.sh`) and a run command that can be copied and pasted.

**Comment by pemaxim** [comment]
@andypotanin Done.

**Comment by pemaxim** [comment]
Done
